// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHMPCE3QxCh0VKCQo2o7LMEt13hvd0D_8',
    appId: '1:324581965178:web:97230ee363c9951f96eac3',
    messagingSenderId: '324581965178',
    projectId: 'hma-beta',
    authDomain: 'hma-beta.firebaseapp.com',
    storageBucket: 'hma-beta.appspot.com',
    measurementId: 'G-TH9V5KZJY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi5LBXRgCr2kGH-eZLeGO4-Aabi1Wn3NA',
    appId: '1:324581965178:android:905009d02293051096eac3',
    messagingSenderId: '324581965178',
    projectId: 'hma-beta',
    storageBucket: 'hma-beta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_e_hSPP9ocfCb8imWP3U1u275wuI_lb8',
    appId: '1:324581965178:ios:4117b677bdeb1eae96eac3',
    messagingSenderId: '324581965178',
    projectId: 'hma-beta',
    storageBucket: 'hma-beta.appspot.com',
    iosClientId: '324581965178-0971bqpmt7jl1s1ai4sa9oi44as394cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_e_hSPP9ocfCb8imWP3U1u275wuI_lb8',
    appId: '1:324581965178:ios:4117b677bdeb1eae96eac3',
    messagingSenderId: '324581965178',
    projectId: 'hma-beta',
    storageBucket: 'hma-beta.appspot.com',
    iosClientId: '324581965178-0971bqpmt7jl1s1ai4sa9oi44as394cd.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
